<?php

require_once dirname(__FILE__) . '/includes/file_remote_video.formatters.inc';
require_once dirname(__FILE__) . '/includes/file_remote_video.widget.inc';

function file_remote_video_autoload_info() {
  return [
    'FileYouTubeStreamWrapper' => 'includes/FileYouTubeStreamWrapper.php',
    'FileVimeoStreamWrapper' => 'includes/FileVimeoStreamWrapper.php',
    'MediaReadOnlyStreamWrapper' => 'includes/MediaReadOnlyStreamWrapper.php',
    'FileRemoteVideoBaseHandler' => 'includes/FileRemoteVideoBaseHandler.inc',
    'FileRemoteVideoYouTubeHandler' => 'includes/FileRemoteVideoYouTubeHandler.inc',
    'FileRemoteVideoVimeoHandler' => 'includes/FileRemoteVideoVimeoHandler.inc',
  ];
}

/**
 * Implements hook_config_info().
 */
function file_remote_video_config_info() {
  $prefixes['file_remote_video.settings'] = [
    'label' => t('File Remote Video Settings'),
    'group' => t('Configuration'),
  ];
  return $prefixes;
}

/**
 * Implements hook_menu().
 */
function file_remote_video_menu() {
  return [
    'admin/config/media/file-remote-video-settings' => [
      'title' => t('Global Remote Video Settings'),
      'page callback' => 'backdrop_get_form',
      'page arguments' => ['file_remote_video_settings_form'],
      'access arguments' => ['administer file types'],
    ],
  ];
}

/**
 * Implements hook_stream_wrappers().
 */
function file_remote_video_stream_wrappers() {
  $stream_wrappers = [
    'youtube' => [
      'name' => t('YouTube Video'),
      'class' => 'FileYouTubeStreamWrapper',
      'description' => 'Provides a YouTube wrapper for Backdrop core files',
      'type' => STREAM_WRAPPERS_READ_VISIBLE
    ],
    'vimeo' => [
      'name' => t('Vimeo Video'),
      'class' => 'FileVimeoStreamWrapper',
      'description' => 'Provides a Vimeo wrapper for Backdrop core files',
      'type' => STREAM_WRAPPERS_READ_VISIBLE
    ]
  ];
  return $stream_wrappers;
}

/**
 * Implements hook_remote_video_handlers().
 */
function file_remote_video_remote_video_handlers() {
  $handlers = [
    'vimeo' => [
      'class' => 'FileRemoteVideoVimeoHandler',
    ],
    'youtube' => [
      'class' => 'FileRemoteVideoYouTubeHandler',
    ],
  ];
  return $handlers;
}

function file_remote_video_get_remote_video_handlers() {
  $handlers = [];
  foreach (module_implements('remote_video_handlers') as $module) {
    $handlers = array_merge($handlers, module_invoke($module, 'remote_video_handlers'));
  }
  return $handlers;
}

function file_remote_video_form_file_manage_form_alter(&$form, &$form_state) {
  if (isset($form_state['file'])) {
    $file = $form_state['file'];
    if (file_remote_video_file_is_remote_video($file)) {
      $form['file_remote_video'] = [
        '#type' => 'fieldset',
        '#title' => t('Remote Video'),
        '#prefix' => '<div id="file-remote-video-ajax-wrapper">',
        '#suffix' => '</div>',
      ];
      $form['file_remote_video']['messages'] = [
        '#prefix' => '<div id="file-remote-video-messages">',
        '#markup' => '',
        '#suffix' => '</div>'
      ];
      $form['file_remote_video']['thumbnail'] = [
        '#markup'=> theme('file_remote_video_form_thumbnail', ['file' => $file]),
      ];
      $form['file_remote_video']['fetch_metadata'] = [
        '#type' => 'button',
        '#value' => t('Fetch File Metadata'),
        '#limit_validation_errors' => [],
        '#ajax' => [
          'callback' => 'file_remote_video_ajax_fetch_file_metadata',
          'wrapper' => 'file-remote-video-ajax-wrapper',
        ],
      ];
    }
  }
}

/**
 * Implements hook_entity_presave()
 */
function file_remote_video_entity_presave($entity, $type) {
  if ($type == 'file') {
    $file = $entity;
    // On first save, try to save and fetch file metadata
    if (empty($file->fid) && file_remote_video_file_is_remote_video($file)) {
      file_remote_video_fetch_file_metadata($file);
    }
  }
}

function file_remote_video_ajax_fetch_file_metadata($form, $form_state) {
  $file = $form_state['file'];
  if (file_remote_video_file_is_remote_video($file)) {
    $fetched = file_remote_video_fetch_file_metadata($file);
    $saved = FALSE;
    if ($fetched) {
      $saved = $file->save();
    }
    if ($fetched && $saved) {
      backdrop_set_message(t('Metadata saved successfully'));
    }
    else {
      backdrop_set_error(t('Error saving metadata'));
    }
  }
  $form['file_remote_video']['thumbnail'] = [
    '#markup'=> theme('file_remote_video_form_thumbnail', ['file' => $file]),
  ];
  $form['file_remote_video']['messages']['#markup'] = theme('status_messages');
  return $form['file_remote_video'];
}

function file_remote_video_fetch_file_metadata($file) {
  if (!file_remote_video_file_is_remote_video($file)) {
    backdrop_set_message(t('File is not a remote video'), 'error');
    return;
  }
  $stream_wrapper = file_stream_wrapper_get_instance_by_uri($file->uri);
  $success = FALSE;
  try {
    $data = $stream_wrapper->getOEmbed();
    if (isset($data['thumbnail_url'])) {
      if (!isset($file->metadata)) {
        $file->metadata = [];
      }
      $file->metadata['thumbnail_url'] = $data['thumbnail_url'];
      $file->metadata['thumbnail_width'] = $data['thumbnail_width'];
      $file->metadata['thumbnail_height'] = $data['thumbnail_height'];
      $success = TRUE;
    }
  }
  catch (throwable $e) {
    $success = FALSE;
    $error_message = $e->getMessage();
    backdrop_set_message($error_message, 'error');
  }
  return $success;
}

function file_remote_video_file_is_remote_video($file) {
  $remote_stream_wrappers = file_remote_video_stream_wrappers();
  $stream_wrapper_classes = [];
  foreach ($remote_stream_wrappers as $wrapper) {
   $stream_wrapper_classes[] = $wrapper['class'];
  }
  $stream_wrapper = file_stream_wrapper_get_instance_by_uri($file->uri);
  $stream_wrapper_class = get_class($stream_wrapper);
  return in_array($stream_wrapper_class, $stream_wrapper_classes);
}

/**
 * Implements hook_theme().
 */
function file_remote_video_theme($existing, $type, $theme, $path) {
  return array(
    'file_remote_video_widget' => [
      'file' => 'file_remote_video.theme.inc',
      'render element' => 'element',
    ],
    'file_remote_video_youtube' => array(
      'variables' => array('uri' => NULL, 'options' => array()),
      'file' => 'file_remote_video.theme.inc',
      'path' => $path . '/themes',
      'template' => 'file-remote-video-youtube',
    ),
    'file_remote_video_vimeo' => array(
      'variables' => array('uri' => NULL, 'options' => array()),
      'file' => 'file_remote_video.theme.inc',
      'path' => $path . '/themes',
      'template' => 'file-remote-video-vimeo',
    ),
    'file_remote_video_form_thumbnail' => [
      'variables' => ['file' => NULL],
      'file' => 'file_remote_video.theme.inc',
    ],
  );
}

function file_remote_video_settings_form($form, &$form_state) {
  $config = config('file_remote_video.settings');
  $settings = $config->getData();
  $youtube_fieldset = file_remote_video_field_formatter_settings_form_youtube_fieldset($settings['youtube']);
  $form['youtube'] = $youtube_fieldset['youtube'];
  $vimeo_fieldset = file_remote_video_field_formatter_settings_form_vimeo_fieldset($settings['vimeo']);
  $form['vimeo'] = $vimeo_fieldset['vimeo'];
  $form['submit'] = [
    '#type' => 'submit',
    '#value' => t('Save Player Config'),
  ];

  return $form;
}

function file_remote_video_settings_form_submit($form, &$form_state) {
  $config = config('file_remote_video.settings');
  $config_settings = $config->getData();
  $form_values = array_merge($config_settings, $form_state['values']);
  $settings = [
    'youtube' => $form_values['youtube'],
    'vimeo' => $form_values['vimeo'],
  ];
  $config->setData($settings);
  $config->save();
  backdrop_set_message(t('Configuration saved!'));
}

/**
 * Returns a file object which can be saved.
 *
 * @param string $uri
 *   A string containing the URI, path, or filename.
 * @return object|bool
 *   A file object, or FALSE on error.
 *
 */
function file_remote_video_load_or_create_video_by_uri($uri) {
  $files = file_load_multiple([], ['uri' => $uri]);
  $file = !empty($files) ? reset($files) : FALSE;
  if (empty($file)) {
    global $user;
    $values = [
      'uid' => $user->uid,
      'status' => FILE_STATUS_PERMANENT,
      'uri' => $uri,
      'mimetype' => file_get_mimetype($uri),
      'timestamp' => REQUEST_TIME,
    ];
    $file = new File($values);
  }
  return $file;

}

function file_remote_video_entity_property_info_alter(&$entity_info) {
  $entity_info['file']['properties']['video_thumbnail'] = [
    'label' => t('Video Thumbnail'),
    'type' => 'text',
    'computed' => TRUE,
    'getter callback' => 'file_remote_video_file_get_video_thumbnail',
    'entity views field' => TRUE,
    'sanitized' => TRUE,
  ];
}

function file_remote_video_file_get_video_thumbnail($file) {
  $icon_path = backdrop_get_path('module', 'file_remote_video') . '/images/icon-video.svg';
  $thumbnail = theme('image', [
    'path' => $icon_path,
    'width' => 100,
    'height' => 100,
    'alt' => t('Video Icon'),
  ]);
  if (file_remote_video_file_is_remote_video($file)) {
    if (isset($file->metadata['thumbnail_url'])) {
      $vars = [
        'path' => $file->metadata['thumbnail_url'],
        'alt' => $file->filename,
      ];
      if (isset($file->metadata['thumbnail_width'])) {
        $vars['width'] = $file->metadata['thumbnail_width'];
      }
      if (isset($file->metadata['thumbnail_height'])) {
        $vars['height'] = $file->metadata['thumbnail_height'];
      }
      $thumbnail = theme('image', $vars);
    }
  }
  return $thumbnail;
}
